### PR TITLE
Updating bs-platform

### PR DESCRIPTION
**Pull request by broerjuang**
I update bs-platform from `2.2.2` to `3.1.5` and remove warning due to the usage of `Js.boolean`. I plan to update the `bs-react-native` to another diff. 

Btw, thanks for starting this!

### CODE REVIEW

**Comment by FiberJW** [comment]
I'm maintaining a more up-to-date version of this library here: https://github.com/FiberJW/reason-expo. It has all of the changes you're about to propose and more!

**Comment by broerjuang** [comment]
Wow cool @FiberJW will fork your repo then.

**Comment by fxfactorial** [comment]
@FiberJW Oh okay, I didn't know you decided to not continue maintaining this repo. 👍

**Comment by FiberJW** [comment]
Yeah it's easier to iterate and push out more versions with my own fork and I didn't wanna bug you too much with a bunch of endless changes for you to review 👌

**Comment by fxfactorial** [comment]
sure, to be clear though, you had full commit access and push. I'm not dealing with this project any more, shoudl write that somewhere as deprecated.

**Pull request closed without merging**
